"""lists table

Revision ID: 1403da776fe1
Revises: cfdc1796f7f6
Create Date: 2020-01-07 23:52:06.078921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1403da776fe1'
down_revision = 'cfdc1796f7f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_list_created_at'), 'gift_list', ['created_at'], unique=False)
    op.create_index(op.f('ix_gift_list_creator_id'), 'gift_list', ['creator_id'], unique=False)
    op.create_table('users_to_giftlists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['gift_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'list_id')
    )
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'created_at')
    op.drop_table('users_to_giftlists')
    op.drop_index(op.f('ix_gift_list_creator_id'), table_name='gift_list')
    op.drop_index(op.f('ix_gift_list_created_at'), table_name='gift_list')
    op.drop_table('gift_list')
    # ### end Alembic commands ###
