"""add gifts

Revision ID: 4c0ce790838d
Revises: d9e2be647e2d
Create Date: 2020-01-19 20:33:43.113570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0ce790838d'
down_revision = 'd9e2be647e2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('purchased', sa.Boolean(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_created_at'), 'gift', ['created_at'], unique=False)
    op.create_index(op.f('ix_gift_creator_id'), 'gift', ['creator_id'], unique=False)
    op.create_index(op.f('ix_gift_recipient_id'), 'gift', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_recipient_id'), table_name='gift')
    op.drop_index(op.f('ix_gift_creator_id'), table_name='gift')
    op.drop_index(op.f('ix_gift_created_at'), table_name='gift')
    op.drop_table('gift')
    # ### end Alembic commands ###
